defaults: &defaults
  docker:
    - image: bepsays/ci-goreleaser:1.1700.600
  environment:
    CGO_ENABLED: "0"

version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    <<: *defaults
    steps:
      - checkout:
          path: hugo
      - run:
          command: |
            git clone git@github.com:gohugoio/hugoDocs.git
            cd hugo
            go mod download
            sleep 5
            go mod verify
      - persist_to_workspace:
          root: .
          paths: .
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /root/project
      - run:
          command: |
            cd hugo
            git config --global user.email "vlad.nixx@gmail.com"
            git config --global user.name "jellybot"
            go run -tags release main.go release -r ${CIRCLE_BRANCH}
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  version: 2
  release:
    jobs:
      - build:
          filters:
            branches:
              only: /release-.*/
      - hold:
          type: approval
          requires:
            - build
      - release:
          context: org-global
          requires:
            - hold